# Generated by Django 4.1.2 on 2022-10-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_name',
        ),
        migrations.AddField(
            model_name='owns',
            name='device_name',
            field=models.CharField(default='userdevice', max_length=20),
        ),
    ]
